### ISSUE TITLE
Applied to other data sets

### ISSUE THREAD

**Issue by fuchao01** [StanfordVL/RubiksNet#2]
I want to train on other data sets，When will the training code be provided？

**Comment by shyamal-b** [comment]
We've added an example [fine-tuning script](https://github.com/StanfordVL/RubiksNet/blob/master/scripts/example_finetune.py) to the repo now and updated the [README](https://github.com/StanfordVL/RubiksNet#kinetics), let us know if you have any further questions. Thanks!
